version: 2
updates:
- package-ecosystem: 'npm'
  directory: '/'
  schedule:
    interval: "monthly"
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - skip-changelog
  - dependencies
  ignore:
  - dependency-name: 'eslint*'
  - dependency-name: 'prettier*'
  rebase-strategy: disabled
- package-ecosystem: github-actions
  directory: '/functions'
  schedule:
    interval: "monthly"
    time: "04:00"
  labels:
    - skip-changelog
    - dependencies
