# Testing the code base against the Meilisearch pre-releases
name: Pre-Release Tests

# Will only run for PRs and pushes to bump-meilisearch-v*
on:
  push:
    branches: [bump-meilisearch-v*]
  pull_request:
    branches: [bump-meilisearch-v*]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['20']
    name: integration-tests (Node.js ${{ matrix.node }})
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install:functions
      - name: Run tests with coverage
        run: yarn test:coverage
