name: publish to npm
on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Check release validity
        run: sh .github/scripts/check-release.sh
      - name: Install dependencies
        run: yarn && yarn install:functions
      - name: Publish with latest tag
        if: "!github.event.release.prerelease"
        run:
          npm publish functions
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish with beta tag
        if: "github.event.release.prerelease"
        run:
          npm publish functions --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
